services:
  blazorapp2:
    container_name: blazorapp2
    build:
      context: .
      dockerfile: BlazorApp2/Dockerfile
    restart: always
    environment:
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "8084:80"
